LiveRamp/jack

- src/java/com/rapleaf/jack/test_project/database_1/impl/BaseCommentPersistenceImpl.java
- src/java/com/rapleaf/jack/test_project/database_1/models/Comment.java
- src/rb/field_defn.rb
prevents causing conflicts when you change timezones
@bpodgursky
> make datetime fields not depend on user's time settings

- pom.xml
@seancarr 
I don't think jack has the capability to log right now, so we'll need to add this to begin with?
> adding slf4j/log4j maven dependencies

- src/rb/templates/model.erb
- test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Image.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Post.java
- test/java/com/rapleaf/jack/test_project/database_1/models/User.java
@pwestling seem ok?  two constructors were not setting associations.
> add missing associations

- src/rb/templates/db_impl.erb
- src/rb/templates/db_interface.erb
- test/java/com/rapleaf/jack/test_project/database_1/IDatabase1.java
- test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java
> Make it possible to retrieve IDatabases from DatabaseImpl

- src/java/com/rapleaf/jack/AttributesWithId.java
- src/java/com/rapleaf/jack/ModelWithId.java
- src/java/com/rapleaf/jack/queries/Record.java
- src/java/com/rapleaf/jack/util/JackUtility.java
- src/rb/templates/model.erb
- test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Image.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Post.java
- test/java/com/rapleaf/jack/test_project/database_1/models/User.java
Last time I added `getIntId()` to the models, but forgot to do the same for the attributes.
> Add getIntId method for AttributesWithId

- src/java/com/rapleaf/jack/AbstractDatabaseModel.java
- src/java/com/rapleaf/jack/IModelPersistence.java
- src/java/com/rapleaf/jack/queries/AbstractDeleteBuilder.java
- src/java/com/rapleaf/jack/queries/ModelDelete.java
- src/java/com/rapleaf/jack/queries/ModelQuery.java
- src/java/com/rapleaf/jack/queries/WhereClause.java
- src/rb/model_defn.rb
- src/rb/template_processor.rb
- src/rb/templates/delete_builder_impl.erb
- src/rb/templates/persistence_impl.erb
- src/rb/templates/persistence_interface.erb
- test/java/com/rapleaf/jack/TestModelDelete.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/ICommentPersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/IImagePersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/IPostPersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/IUserPersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/impl/BaseCommentPersistenceImpl.java
- test/java/com/rapleaf/jack/test_project/database_1/impl/BaseImagePersistenceImpl.java
- test/java/com/rapleaf/jack/test_project/database_1/impl/BasePostPersistenceImpl.java
- test/java/com/rapleaf/jack/test_project/database_1/impl/BaseUserPersistenceImpl.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Image.java
- test/java/com/rapleaf/jack/test_project/database_1/models/Post.java
- test/java/com/rapleaf/jack/test_project/database_1/models/User.java
- test/java/com/rapleaf/jack/test_project/database_1/query/CommentDeleteBuilder.java
- test/java/com/rapleaf/jack/test_project/database_1/query/ImageDeleteBuilder.java
- test/java/com/rapleaf/jack/test_project/database_1/query/PostDeleteBuilder.java
- test/java/com/rapleaf/jack/test_project/database_1/query/UserDeleteBuilder.java
- test/test_project/database_1/db/schema.rb
- test/test_project/database_2/db/schema.rb
@tuliren @bpodgursky: This is to add support for building DELETE statements from generated models.
> Delete statement support

- src/java/com/rapleaf/jack/queries/WhereConstraint.java
> updated to add backticks

- src/java/com/rapleaf/jack/AbstractDatabaseModel.java
- src/java/com/rapleaf/jack/queries/where_operators/JackMatchers.java
- src/java/com/rapleaf/jack/queries/where_operators/NoOp.java
- test/java/com/rapleaf/jack/TestModelQuery.java
@tuliren, can you test it as I'm still having trouble with my ruby environment?
> Handle Not In operator with empty collection

- test/java/com/rapleaf/jack/test_project/IDatabases.java
- test/java/com/rapleaf/jack/test_project/database_1/IDatabase1.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/ICommentPersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/IImagePersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/ILockableModelPersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/IPostPersistence.java
- test/java/com/rapleaf/jack/test_project/database_1/iface/IUserPersistence.java
> regenerate test project files

- src/rb/association_defn.rb
- src/rb/field_defn.rb
- src/rb/hash_regex_helpers.rb
- src/rb/jack.rb
- src/rb/model_defn.rb
- src/rb/models_dir_processor.rb
- src/rb/requires.rb
- src/rb/schema_rb_parser.rb
- src/rb/templates/create_method.erb
- test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java
- test/test_project/database_1/db/schema.rb
Reverts LiveRamp/jack#160
Tryin' again.
> Revert "Revert "Support for ruby2""

- test/create_databases.sh
- test/migrate_project.sh
- test/regen_code.sh
- test/select-dbms.sh
- test/update_database_yml.sh
> add -l flag to shell scripts

- test/java/com/rapleaf/jack/BaseDatabaseModelTestCase.java
- test/java/com/rapleaf/jack/TestAbstractDatabaseModel.java
- test/java/com/rapleaf/jack/TestDbImpl.java
- test/java/com/rapleaf/jack/TestLazyLoadPersistence.java
- test/java/com/rapleaf/jack/TestModelDelete.java
- test/java/com/rapleaf/jack/TestModelQuery.java
- test/java/com/rapleaf/jack/TestModelWithID.java
Replace the deprecated JUnit 3 style TestCase usage and update imports.
@bpodgursky
> Update tests to use JUnit 4 style annotations

- src/java/com/rapleaf/jack/IDb.java
- src/rb/templates/db_impl.erb
- test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java
@tuliren  switch to the new lazy implementation for the existing deleteAll, get rid of new method.
> use new implementation for delete all

- test/test_project/database_1/Gemfile.mysql
- test/test_project/database_1/Gemfile.postgres
- test/test_project/database_2/Gemfile.mysql
- test/test_project/database_2/Gemfile.postgres
Otherwise bundler keeps trying to change Gemfile.lock to use Rails 3.
@bpodgursky
> Update Gemfiles in test projects to use Rails 4

- src/java/com/rapleaf/jack/queries/Records.java
@tuliren It'd be nice to be able to use streams with Records without having to wrap it in a collection.
> add stream method to Records

- jack-core/src/com/rapleaf/jack/transaction/DbMetricsImpl.java
- jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java
- jack-core/src/com/rapleaf/jack/transaction/TransactorMetricsImpl.java
- jack-test/test/java/com/rapleaf/jack/transaction/TestTransactorMetrics.java
The Stopwatch is causing issues with old java versions
> Stopwatch fix

- jack-core/src/rb/templates/persistence_impl.erb
causes compilation error for this template's resultant classes
> accidental removal of JackUtility

- .rspec
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- jack-core/src/rb/database_defn.rb
- jack-core/src/rb/jack.rb
- jack-core/src/rb/models_dir_processor.rb
- jack-core/src/rb/schema_rb_parser.rb
- jack-test/test/java/com/rapleaf/jack/test_project/migration-version.txt
- jack-test/test/rb/database_defn_spec.rb
- jack-test/test/rb/field_defn_spec.rb
- jack-test/test/rb/spec_helper.rb
- jack-test/test/test_project/database_1/app/models/profile.rb
- jack-test/test/test_project/database_1/db/migrate/20180502013029_create_profiles.rb
- jack-test/test/test_project/database_1/db/schema.rb
- jack-test/test/test_project/project.yml
A new key is added to `project.xml` that tells jack to completely ignore the specified tables. No code will be generated for them.
This resolves DMFS-184.
> [DMFS-184] Ignore Tables

- jack-core/src/com/rapleaf/jack/queries/GenericQuery.java
@tuliren object to a convenience method?
> add a convenience method for selecting full models

- jack-core/src/com/rapleaf/jack/DatabaseConnectionConfiguration.java
@tuliren 
This change suggested by @jrhizor:
- adds logging when a yaml is missing
- includes a list of present keys in the missing tag exception
> log missing yamls, missing keys

- jack-test/test/rb/schema_rb_parser_spec.rb
@mharris717, this PR adds tests for `SchemaRbParse` so that #216 can be safely merged.
> test: spec for schema rb parser

- jack-core/src/com/rapleaf/jack/queries/GenericDeletion.java
- jack-core/src/com/rapleaf/jack/queries/GenericQuery.java
- jack-core/src/com/rapleaf/jack/queries/JoinConditionBuilder.java
- jack-core/src/com/rapleaf/jack/queries/JoinableExecution.java
- jack-test/test/java/com/rapleaf/jack/queries/TestGenericDeletion.java
> Deletion with Join

- README.md
- jack-core/pom.xml
- jack-mysql/pom.xml
- jack-postgresql/pom.xml
- jack-redshift/pom.xml
- jack-store/pom.xml
- jack-test/pom.xml
- pom.xml
I'll switch things to 1.4-SNAPSHOT right after this.
> Release version 1.3.0

- jack-core/pom.xml
- jack-mysql/pom.xml
- jack-postgresql/pom.xml
- jack-redshift/pom.xml
- jack-store/pom.xml
- jack-test/pom.xml
- pom.xml
Will update to 1.5.0-SNAPSHOT after release.
> Set versions to 1.4.0 for release.
