LiveRamp/jack

src/java/com/rapleaf/jack/AbstractDatabaseModel.java, src/java/com/rapleaf/jack/BaseDatabaseConnection.java
@seancarr 
I thought it might be cleanest for resetConnection() to optionally take a cause. Open to suggestions, though.
=> passing the cause of the recoverable exception to resetConnection

src/java/com/rapleaf/jack/AbstractDatabaseModel.java, src/java/com/rapleaf/jack/BaseDatabaseConnection.java
@seancarr 
I think this should log most of what people need to investigate root causes in case of connection reset attempts.
I'm also thinking of adding more logging to AbstractDatabaseModel, since there are cases when we ignore SqlExceptions in finally clauses.
=> logging recoverable sql exceptions

pom.xml, src/java/com/rapleaf/jack/queries/Functions.java, test/java/com/rapleaf/jack/TestGenericQuery.java
@bpodgursky found a bug in queries with `Datetime` columns. The bug also applies to `Date` columns.
The issue is the same as [this StackOverflow post](http://stackoverflow.com/questions/10888194/mysql-select-timestamps-between-a-and-b-returning-all-or-0-timestamps). Querying date / datetime columns with long values won't always give the correct result because SQL engine expects date literal for those columns.
Since Jack treats SQL `Datetime` and `Date` as `Long` in Java, the query cannot auto apply the appropriate operations on the long variable. The fix here uses static functions to convert the long value(s) into date or datetime literal(s). For a long `Datetime`, a `java.util.Date` type is constructed and then formatted. For a long `Date`, a `java.sql.Date` type is constructed and …
=> Fix Date and Datetime Query

src/java/com/rapleaf/jack/queries/Record.java, test/java/com/rapleaf/jack/TestGenericQuery.java
Method `getLong` does not consider the case of sql type `java.sql.Date` and this leads to runtime exceptions.
In Jack we use `java.sql.Date` and `java.sql.Timestamp` to represent sql type `Date` and `Datetime` respectively. Since they both extends `java.util.Date`, replacing the `java.sql.Timestamp` check with the `java.util.Date` check can fix this issue. We represent `Datetime` as type long, and won't get the extra resolution (nanosecond resolution beyond three digits) from `Timestamp` anyway. So the conversion from `Timestamp` to `java.util.Date` is safe.
Reference: http://stackoverflow.com/questions/2305973/java-util-date-vs-java-sql-date
=> Fix Type Conversion for Date

src/rb/templates/databases_impl.erb, test/java/com/rapleaf/jack/test_project/DatabasesImpl.java
@bpodgursky @tuliren 
This loads each db lazily instead of at construction time, which makes it possible for projects to only include required databases in the database.yml file.
=> Lazily load each db in DatabasesImpl

src/java/com/rapleaf/jack/AssociationType.java, src/java/com/rapleaf/jack/DefaultAssociationMetadata.java, src/java/com/rapleaf/jack/IAssociationMetadata.java, src/java/com/rapleaf/jack/IModelAssociationMetadata.java, src/rb/templates/model.erb, test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java, test/java/com/rapleaf/jack/test_project/database_1/models/Image.java, test/java/com/rapleaf/jack/test_project/database_1/models/Post.java, test/java/com/rapleaf/jack/test_project/database_1/models/User.java
The ability to create this data lets us avoid using reflection to do
generic traverasals of the database "graph" for certain applications
=> add ability to get association metadata from models

src/java/com/rapleaf/jack/queries/Functions.java
There is a bug in function `DATETIME`. It uses `hh` to convert a long value to a datetime literal. In `DateTimeFormat`, however, `hh` means clockhour of halfday, which ranges from 1 to 12. It will incorrectly create an AM datetime literal for a PM time.
Instead, `HH` should be used, which ranges from 0 to 23.
@SLieve and @jrhizor, this is why your queries returned nothing. Sorry about the inconvenience.
=> Fix of DATETIME

src/java/com/rapleaf/jack/queries/WhereConstraint.java, src/rb/templates/persistence_impl.erb, src/rb/templates/query_builder_impl.erb, test/java/com/rapleaf/jack/TestModelQuery.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseCommentPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseImagePersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BasePostPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseUserPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/query/CommentQueryBuilder.java, test/java/com/rapleaf/jack/test_project/database_1/query/ImageQueryBuilder.java, test/java/com/rapleaf/jack/test_project/database_1/query/PostQueryBuilder.java, test/java/com/rapleaf/jack/test_project/database_1/query/UserQueryBuilder.java
Make it possible to do:
```
MyModel.query().whereId(myWhereClause).find()
```
Today it is only supported for non-id fields
=> Support where clauses for ids

src/java/com/rapleaf/jack/LazyLoadPersistence.java, src/rb/templates/db_impl.erb, test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java, test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java, test/java/com/rapleaf/jack/test_project/database_1/models/Image.java, test/java/com/rapleaf/jack/test_project/database_1/models/Post.java, test/java/com/rapleaf/jack/test_project/database_1/models/User.java, test/test_project/database_1/db/schema.rb, test/test_project/database_2/db/schema.rb
This change will make it easier to delete table from the DB so that you don't have to synchronize the migration with the java code deploy.
The code will only fail if you try to *use* a table which doesn't exist in the db instead of failing on Database instantiation.
=> Lazy load table metadata

src/java/com/rapleaf/jack/LazyLoadPersistence.java, test/java/com/rapleaf/jack/BaseDatabaseModelTestCase.java, test/java/com/rapleaf/jack/TestLazyLoadPersistence.java
@tuliren @bpodgursky @michel-tricot: I added some test cases for and fixed an issue in which once caching is disabled on a lazily loaded model persistence, it cannot be re-enabled.
=> Allowing disabling then re-enabling caching of lazily loaded persistences

Gemfile.lock, src/java/com/rapleaf/jack/queries/AbstractTable.java, src/java/com/rapleaf/jack/queries/GenericQuery.java, src/java/com/rapleaf/jack/queries/Record.java, src/java/com/rapleaf/jack/queries/Records.java, src/java/com/rapleaf/jack/queries/Table.java, src/rb/templates/model.erb, test/java/com/rapleaf/jack/TestGenericQuery.java, test/java/com/rapleaf/jack/test_project/database_1/models/Comment.java, test/java/com/rapleaf/jack/test_project/database_1/models/Image.java, test/java/com/rapleaf/jack/test_project/database_1/models/Post.java, test/java/com/rapleaf/jack/test_project/database_1/models/User.java
@bpodgursky, this pull request incorporates your `JackUtil` into the `Record` and `Records` classes. The main change is that the new method takes one `Table` parameter, instead of the model and attributes types. Those information is wrapped in `Table`. So the method call is slightly simplier. A bug fix is also included in this pull request. It turns out that SQL sometimes returns double value as `BigDecimal` or `Float`. These types are put in special checks.
Since `Attributes` is already a plural word, the methods for retrieving attributes are the same for `Record` and `Records`: `Record#getAttributes` returns one `Attributes`, and `Records#getAttributes` returns a list of it.
If the user tries to retrieve the model / attributes of a table whose fields do not exist in the `Record`, `null` …
=> Retrieve Model and Attributes from Record

src/java/com/rapleaf/jack/queries/AggregatedColumn.java
The return type of COUNT query should be integer. `Integer.MAX_VALUE` is more than two billion, and should be enough to cover the number of entries in a database.
=> Integer COUNT

src/rb/model_defn.rb
I suspect this is all we need. 
```
$ rbenv version
1.9.3-p551 (set by /Users/rgeorge/code/jack/.ruby-version)
rgeorge@Roshans-MacBook-Pro:~/code/jack [constantify-uid] 17:23
$ test/regen_code.sh
6213989608937906012
-2156535913590481279
-3351451520429699622
5384617403533794948
2267084843778072603
2267084843778072603
-399049548729901546
-452436965662476312
-966057050205502149
7482296567648746981
rgeorge@Roshans-MacBook-Pro:~/code/jack [constantify-uid] 17:23
$ rm .ruby-version
rgeorge@Roshans-MacBook-Pro:~/code/jack [constantify-uid] 17:23
$ test/regen_code.sh
6213989608937906012
-2156535913590481279
-3351451520429699622
5384617403533794948
2267084843778072603
2267084843778072603
-399049548729901546
-452436965662476312
-966057050205502149
7482296567648746981
```
=> Make UID the same on 1.8.7 and 1.9.3

src/java/com/rapleaf/jack/IDb.java, src/rb/templates/db_interface.erb
This allows us to write code that operates on any DB. Our use case is generic status setting across models.
=> Move createQuery up to IDb interface

src/java/com/rapleaf/jack/AbstractDatabaseModel.java, src/java/com/rapleaf/jack/IModelPersistence.java, test/java/com/rapleaf/jack/TestModelWithID.java
For tests that rely on updating the database, it would be extremely helpful
to be able to set an update time for the updated_at column to be set to,
rather than having this hardcoded into the save method. This adds that
while also keeping the default behavior.
@bpodgursky
=> Add ability to specify update time for testing

src/rb/templates/databases_iface.erb, src/rb/templates/db_interface.erb, src/rb/templates/persistence_interface.erb
The `public` specifier Jack puts on its interface methods is unnecessary and
clutters the output code. This change removes that.
@bpodgursky
=> Remove redundant `public` specifiers from Jack-generated interfaces

src/rb/models_dir_processor.rb
@tuliren @bpodgursky -- Can you guys take a look? Tested this with rldb and workflow_db. Caused a minor change in rldb, but I think it's the correct behavior.
The intention here is to add support for namespaced models. We want to do this as we're adding new DBs to avoid naming conflicts.
This PR does two things:
1. Looks for models in recursive subdirs of models dir. Previously only looked for `.rb` files in `app/models`.
2. Strips namespaces from class names (e.g., `MyNamespace::Model` --> `Model`). This assumes that the table naming convention for namespaced models is `MyNamespace::Model` is `models` instead of `my_namespace_models`. I don't see a nice way around this without completely refactoring Jack to not use dumb regex parsing.
=> add support for namespaced models

test/update_database_yml.sh
If update_database_yml.sh is called multiple times, it will leave
a syntax error in database.yml. This fixes that.
@bpodgursky
=> Fix syntax error generation in database.yml

src/rb/templates/persistence_impl.erb, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseCommentPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseImagePersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseLockableModelPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BasePostPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseUserPersistenceImpl.java
Using double curly braces to initialize map and list objects is an anti-pattern
that we should never use. See https://blog.jooq.org/2014/12/08/dont-be-clever-the-double-curly-braces-anti-pattern/
for a detailed discussion. Essentially the problems are:
* It's not very readable.
* It creates a separate class for each instance, which adds overhead in the
ClassLoader.
* It can create memory leaks, since the new objects retain a reference to
their enclosing class, which leaves a high potential for circular
references.
This removes this anti-pattern from our jack-generated code.
@bpodgursky
=> Get rid of double curly brace initialization in persistence impls

src/java/com/rapleaf/jack/queries/GenericQuery.java, src/java/com/rapleaf/jack/queries/Records.java, src/java/com/rapleaf/jack/tracking/NoOpAction.java, src/java/com/rapleaf/jack/tracking/PostQueryAction.java, src/java/com/rapleaf/jack/tracking/QueryStatistics.java, src/rb/templates/databases_impl.erb, src/rb/templates/db_impl.erb, test/java/com/rapleaf/jack/test_project/DatabasesImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java
This will allow us to capture query execution time to report it elsewhere. It's simplistic so that we don't have pull in any JARs just to tell how long something took to execute.
This allows adding `PostQueryAction`s like 
```
public class MyStatsClient implements PostQueryAction {
@Override
public void perform(QueryStatistics statistics) {
final StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();
final StackTraceElement containingClass = stackTrace[3];
yFavouriteStatsClient.gauge(containingClass.getClassName(), statistics.executionTimeNanos);
}
}
```
=> Add rudimentary query performance tracking to Jack

src/java/com/rapleaf/jack/IDb.java, src/java/com/rapleaf/jack/queries/GenericQuery.java, src/java/com/rapleaf/jack/queries/QueryFetcher.java, src/rb/templates/db_impl.erb, test/java/com/rapleaf/jack/TestDbImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java
This is a means to allow queries that aren't possible in Jack's model
while still retaining the ability to create the common `Records` objects
that are used by Jack.
The alternative, exposing the connection, is likely to cause confusion
since the ORM's behaviour is directly coupled to connection state and
managing autoCommit on both seemingly independently (but not really)
is confusing.
This is intended to be analogous to ActiveRecord's `find_by_sql`. [Example Usage](https://github.com/LiveRamp/jack/pull/166/files#diff-4d0daeb0c666e8482208be3cc784e44cR34).
=> Add a SQL escape hatch that provides object hydration alone

src/java/com/rapleaf/jack/BaseDatabaseConnection.java, src/java/com/rapleaf/jack/DatabaseConnection.java, src/java/com/rapleaf/jack/DatabaseConnectionConfiguration.java
Allow the setting or overriding of all Jack connection configurations by
preferring data from environment variables and system properties. This
allows the use of Jack in situations where a config file is hard to
supply, and allows overriding specific properties for non-standard use
cases.
@roshan and @sidoh, as the most recent contributor and as a dev tools guy, if you're willing to quickly review I'd appreciate it.
=> allow overriding configs via environment

.travis.yml, pom.xml
- Replaced java environment with ruby so that we can specify ruby version by the built-in rvm.
- Added test environment for jdk8. Each build now includes two jobs, one for jdk7, and one for 8.
=> Travis CI with Ruby 2.3

src/java/com/rapleaf/jack/queries/Column.java, src/java/com/rapleaf/jack/queries/where_operators/Match.java, test/java/com/rapleaf/jack/TestGenericQuery.java
@rfaugeroux @tuliren 
I'm doing this because I would like to use a join that involves using a 'contains' condition against a column name instead of a string literal for another task.
=> changes for matching columns

src/java/com/rapleaf/jack/AbstractDatabaseModel.java, src/java/com/rapleaf/jack/IModelPersistence.java, src/rb/templates/db_impl.erb, test/java/com/rapleaf/jack/TestAbstractDatabaseModel.java, test/java/com/rapleaf/jack/test_project/database_1/impl/BaseCommentPersistenceImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java
@tuliren 
Since we're seeing major slowdowns in truncate speed when upgrading to 5.6/5.7, I want to see if it's faster to check if the table is empty before truncating.  Since most tests only populate 2-3 couple tables out of 550+, it will avoid the vast majority of truncates, albeit at the cost of extra queries.  
If this is significantly better, I'd probably want to replace deleteAll entirely with this implementation, but I want to test out performance first.
=> Delete all lazy

src/java/com/rapleaf/jack/IDb.java, src/rb/templates/db_impl.erb, test/java/com/rapleaf/jack/TestDbImpl.java, test/java/com/rapleaf/jack/test_project/database_1/impl/Database1Impl.java
@seancarr, I am working on adding a db connection pool, but I am not sure how soon it will be done. Meanwhile, can we use the `close` method to prevent a workflow from holding too many idle connections?
=> Add close method on db interface

src/java/com/rapleaf/jack/BaseDatabaseConnection.java
@seancarr, the current `close` method is not idempotent. If this method is called twice on a connection, the second call will create a new connection and close it immediately.
=> Idempotent Close Method

src/java/com/rapleaf/jack/transaction/IExecution.java, src/java/com/rapleaf/jack/transaction/IQuery.java
The purpose of this change is to allow the transactor catch any type of exception. Previously, IExecution and IQuery only throw IOException, and all the other exceptions still need to be manually handled by the user.
@vpatel
=> IExecution and IQuery Exception

src/java/com/rapleaf/jack/transaction/ITransactor.java, src/java/com/rapleaf/jack/transaction/TransactorImpl.java, test/java/com/rapleaf/jack/transaction/TestDbTransactorImpl.java, test/java/com/rapleaf/jack/transaction/TestMockTransactorImpl.java
@tuliren, @roshan and @bpodgursky, what do you guys think about it?
It is backward compatible so we should be able to clean the usages of `execute(IQuery query)` before getting rid of it.
(Also, could I be (re?)added as a member of jack?)
=> added query method and deprecate execute(IQuery query)

src/java/com/rapleaf/jack/BaseDatabaseConnection.java
@tuliren the goal is to avoid making a connection unusable and ending up in a bad state when trying to reset the connection when in the middle of a transaction
FYI @seancarr @rfaugeroux
=> set the connection to null to avoid getting stuck

jack-core/src/com/rapleaf/jack/transaction/ITransactor.java, jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java
@npoulallion, I think it's time to remove these methods. I will merge it after cleaning up existing use cases in the production.
=> Remove deprecated transactor methods

jack-core/src/com/rapleaf/jack/transaction/DbMetrics.java, jack-core/src/com/rapleaf/jack/transaction/DbMetricsImpl.java, jack-core/src/com/rapleaf/jack/transaction/DbPoolManager.java, jack-core/src/com/rapleaf/jack/transaction/MockDbMetrics.java, jack-core/src/com/rapleaf/jack/transaction/TransactorMetricsImpl.java, jack-test/test/java/com/rapleaf/jack/transaction/TestDbMetrics.java, jack-test/test/java/com/rapleaf/jack/transaction/TestTransactorMetrics.java
There was a null pointer exception in the transactor metrics priority queue.
I assume this was due to a synchronization issue, I handled it and handled the null exception separately.
=> Bug in transactor Metrics

Gemfile, Gemfile.lock, jack-core/src/com/rapleaf/jack/queries/GenericQuery.java, jack-test/test/java/com/rapleaf/jack/queries/TestGenericQuery.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/models/TestStore.java
Adds a new generic query method, `selectDistinct`, which results in a `SELECT DISTINCT` query instead of `SELECT`. This is necessary for filtering out duplicate rows in queries with joins.
=> Add SELECT DISTINCT support

jack-core/src/rb/database_defn.rb, jack-core/src/rb/jack.rb
@tuliren 
This is very technically incorrect in that if it's processing multiple databases, it doesn't unload the inflections in-between.  But we don't do that, so I'm inclined to not care.
=> small change to let projecy.yml point jack to an inflections file

jack-core/src/com/rapleaf/jack/AbstractDatabaseModel.java, jack-core/src/rb/templates/create_method.erb, jack-core/src/rb/templates/persistence_impl.erb, jack-test/test/java/com/rapleaf/jack/LoggingMysqlConnection.java, jack-test/test/java/com/rapleaf/jack/TestAbstractDatabaseModel.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/impl/BaseCommentPersistenceImpl.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/impl/BaseImagePersistenceImpl.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/impl/BaseLockableModelPersistenceImpl.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/impl/BasePostPersistenceImpl.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/impl/BaseTestStorePersistenceImpl.java, jack-test/test/java/com/rapleaf/jack/test_project/database_1/impl/BaseUserPersistenceImpl.java
@bpodgursky, I guess this can prevent the exception throwing from newly added optional fields if you only create new models, instead of creating the basic model first and update the optional fields.
Unit tests have not been added yet.
=> Ignore Null When Inserting New Row

Gemfile, Gemfile.lock, jack-core/src/Gemfile, jack-core/src/Gemfile.lock
`rails`-`3.0.6` and `i18n`-`0.5.0` have security vulnerability issues.
=> Update gem versions

jack-core/src/rb/models_dir_processor.rb
This fix is to handle situations where associations are followed directly by a tab character. For example, when given the following lines in a `model.rb` file:
```
has_many\t\t  :some_name, :dependent => :destroy 
has_many \t\t  :some_other_name, :dependent => :destroy
```
the current regex impl will accept the second line, but not the first. This PR allows it to accept both
=> remove white spaces in model_dir_processor matching keywords

jack-core/src/com/rapleaf/jack/DatabaseConnectionConfiguration.java
Previously, the order for fetching config files was reveresed from "normal". With this change, Jack will
first look for an entire config file stored as a string in the appropriate env var or system property, then for a path to a
config file stored in the appropriate env var or system property, then in default locations.
=> change the order of preference for fetching config files

jack-core/src/com/rapleaf/jack/util/JackUtility.java, jack-test/test/java/com/rapleaf/jack/util/TestJackUtility.java
This is a not-completely-rational attempt to fix the mysterious `NoSuchMethodError` by removing the explicit reference of the complaint method. This is way safer than #220.
```
Exception in thread "main" java.lang.NoSuchMethodError: org.joda.time.DateTime.toString(Lorg/joda/time/format/DateTimeFormatter;)Ljava/lang/String;
at com.rapleaf.jack.util.JackUtility$DateFormatter.apply(JackUtility.java:44)
at com.rapleaf.jack.util.JackUtility$DateFormatter.apply(JackUtility.java:34)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at …
```
=> Avoid Joda DateTimeFormat

jack-core/src/com/rapleaf/jack/queries/WhereClause.java, jack-test/test/java/com/rapleaf/jack/TestModelDelete.java, jack-test/test/java/com/rapleaf/jack/TestModelQuery.java
`NoOp` operator specifies `is not null OR true` in the where clause. Since all where constraints are simply concatenated together, `OR true` makes the query return everything.
This bug is fixed in this PR.
=> Fix NoOp Operator Bug

Gemfile, Gemfile.lock, jack-core/src/Gemfile, jack-core/src/Gemfile.lock, jack-core/src/rb/field_defn.rb, jack-core/src/rb/model_defn.rb, jack-core/src/rb/schema_rb_parser.rb
Only todo is honor FORBIDDEN_FIELD_NAMES, although no such columns appear in our schema.rb. I diffed the output from this against the old output and it was identical.
=> Evaluate schema.rb instead of parsing it like a string

jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java
See [Issue 230](https://github.com/LiveRamp/jack/issues/230) for an explanation of the problem.
The solution is to move the `connection.setAutoCommit(!asTransaction)` into the appropriate `try` blocks.
=> [ISSUE 230] Fix Leaked Connections in TransactorImpl

jack-test/pom.xml
The current pom.xml for jack-test assumes you have write access to your
system bundle. By specifying `--path vendor/bundle`, this does not have
to be the case and increases compatibility.
Also, the earlier syntax was actually ignoring the keyword `install`
from `bundle install`. When using `/bin/sh -c`, the entire shell script
should be passed in as an argument value.
=> Install to private bundle

jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java
All use cases in production have been removed. This change is submitted in a PR only for visibility. It should be safe to merge.
=> Remove deprecated transactor builder methods

jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java, jack-test/test/java/com/rapleaf/jack/transaction/TestTransactorImplBuilder.java
Previously the transactor builder resets all parameters after each build. This seems silly. It is more likely that people would want to keep the configurations when they call the builder multiple times. This PR remove this feature.
=> Remove transactor builder reset

jack-core/src/com/rapleaf/jack/queries/AbstractExecution.java, jack-core/src/com/rapleaf/jack/queries/AbstractTable.java, jack-core/src/com/rapleaf/jack/queries/AggregatedColumn.java, jack-core/src/com/rapleaf/jack/queries/Column.java, jack-core/src/com/rapleaf/jack/queries/GenericInsertion.java, jack-core/src/com/rapleaf/jack/queries/GenericQuery.java, jack-core/src/com/rapleaf/jack/queries/QueryFetcher.java, jack-test/test/java/com/rapleaf/jack/queries/TestAggregatedColumn.java, jack-test/test/java/com/rapleaf/jack/queries/TestColumn.java, jack-test/test/java/com/rapleaf/jack/queries/TestSubQuery.java
@mark-idleman, this PR should allow us to use aggregated columns in subqueries and fix your query issue. An example is in `testAggregatedColumnSubQuery`.
The main idea is that the sql expression of a column should be different for different clauses:
1. Normally it is just the column name.
2. In select clause, when an alias is need, it is in the form of "column AS alias". This is necessary for aggregated columns within a subquery.
3. When retrieving the value from a `ResultSet`, it is just the alias.
I've compared a few implementations, and this one is the shortest that requires the least amount of refactoring.
=> Support aggregated column in subquery

Gemfile, Gemfile.lock, jack-core/src/Gemfile, jack-core/src/Gemfile.lock
There are two ways to fix it.
1. Enforce the build and deploy to use ruby `2.3.0`.
2. Upgrade `activesupport` to `4.2.8`.
=> Fix sonatype branch

jack-core/src/com/rapleaf/jack/queries/ModelDelete.java, jack-core/src/com/rapleaf/jack/queries/ModelQuery.java, jack-test/test/java/com/rapleaf/jack/queries/TestModelDelete.java, jack-test/test/java/com/rapleaf/jack/queries/TestModelQuery.java
It can be dangerous to expose `ModelDelete` to users directly. This PR hides the constructor and force users to construct query or deletion through the model.
=> Mark model query & delete constructors as package private

jack-core/src/com/rapleaf/jack/AbstractDatabaseModel.java, jack-core/src/com/rapleaf/jack/IModelPersistence.java, jack-test/test/java/com/rapleaf/jack/BaseDatabaseModelTestCase.java
Moving this up to the top-level allows us to write code that abstracts
over all Jack models and supports deletes for multiple IDs. This
seems reasonable since we do have `delete(long id)`.
=> Allow deleting multiple records of a model at once

jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java, jack-test/test/java/com/rapleaf/jack/transaction/TestDbTransactorImpl.java
Both methods which execute transactions (`query` and `execute`) only catch `Exception`s, not `Throwables`. As a result, if a `Throwable` is thrown in the middle of a transaction, then we only execute the `finally` block which returns the connection (and we don't explicitly rollback the transaction as we would have done inside the `catch(Exception e)` block. The unfortunate side effect of this behavior is that it commits partially-completed transactions; returning a connection calls `.setAutoCommit(true)` which commits any commands built up during the uncommitted transaction which leaves us with inconsistent state. 
1. remove the `finally` block, and instead return the connection at the end of both the `try` and `catch(Exception e)` blocks. 
2. add a `catch(Throwable t)` block in which we …
=> Handle throwables while executing transactions

jack-core/src/com/rapleaf/jack/DatabaseConnection.java
Current `getConnection()` function immediately throws exception if the SQL server is unreachable. As we migrated to CloudSQL, it needs a retry policy to deal with the downtime of CloudSQL. More details see: [Aim service retries when connecting to bang DB](https://liveramp.atlassian.net/browse/DEVID-997)
=> added getConnection() retry policy

jack-core/pom.xml, jack-core/src/com/rapleaf/jack/DatabaseConnection.java, jack-core/src/com/rapleaf/jack/DatabaseConnectionConfiguration.java, jack-core/src/com/rapleaf/jack/transaction/DbPoolManager.java, jack-test/config/database.mysql.yml, jack-test/test/test_project/database_1/config/database.mysql.yml
`isClosed` is not sufficient to validate connections. You need to check that they are actually still usable, which is what `isValid` does. This PR prevents applications from seeing issues when databases failover and connections are no longer valid.
=> Validate connections before using them and expose validation as config.

jack-core/src/com/rapleaf/jack/queries/GenericQuery.java
I've seen this method being used as a convenience method to use java streams, but in fact, it's doing way more than that. Added a comment to be more specific on what this method is doing.
=> add fetchAsStream method comment

jack-core/src/com/rapleaf/jack/transaction/DbPoolManager.java, jack-core/src/com/rapleaf/jack/transaction/IDbManager.java, jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java, jack-test/test/java/com/rapleaf/jack/transaction/TestDbPoolManager.java, jack-test/test/java/com/rapleaf/jack/transaction/TestDbTransactorImpl.java
If an exception is thrown while attempting to rollback a transaction,
then the connection is never returned to the connection pool. This
slowly leaks connections until there are none left.
=> Fix connection leak caused by exceptions during rollback.

jack-core/src/com/rapleaf/jack/transaction/ITransactor.java, jack-core/src/com/rapleaf/jack/transaction/TransactorImpl.java, jack-core/src/com/rapleaf/jack/util/ExponentialBackoffRetryPolicy.java, jack-test/test/java/com/rapleaf/jack/transaction/TestDbTransactorImpl.java, jack-test/test/java/com/rapleaf/jack/transaction/TestDbTransactorImplRetry.java, jack-test/test/java/com/rapleaf/jack/util/TestExponentialBackoffPolicy.java, jack-test/test/java/com/rapleaf/jack/util/TestQueryRetryPolicy.java
This patch is inspired by #210 - It introduces `ExecutionContext` that allows clients to specify options for every query/update. Currently the two options supported are to run as a transaction (deprecates `queryAsTransaction` and `executeAsTransaction` methods) and set a retry policy on failure. The default behavior remains unchanged, namely, no retries on failure. However, clients can now use the new exponential backoff policy with tunable number of retries and sleep intervals. Users could potentially create their own advanced retry policies by implementing the `ITransactor.RetryPolicy` interface. The policy is executed on failure only after the connection has been invalidated or returned to the pool manager.  
*Example:*
```java
transactor
.asTransaction()
.allowRetries(new …
```
=> Allow clients to request the transactor to retry queries

jack-mysql/pom.xml, jack-postgresql/pom.xml, jack-redshift/pom.xml, jack-store/pom.xml, jack-test/pom.xml, pom.xml
The previous version being used is five years old and numerous bug fixes
have been applied since.  Chief among them is re-enabled support for
fractional seconds.
Jira: INGEST-2133
=> INGEST-2133, Update mysql-connector-java

README.md, docs/release_process.md, jack-core/pom.xml, jack-mysql/pom.xml, jack-postgresql/pom.xml, jack-redshift/pom.xml, jack-store/pom.xml, jack-test/pom.xml, pom.xml
This change simplifies the proces of updating of the module versions by
consolidating them all to a single property.  This follows the example
given in the article [Maven CI Friendly Versions][1].  It also documents the
steps for triggering a release version and advancing the snapshot
version.
Jira: INGEST-2133
[1]: https://maven.apache.org/maven-ci-friendly.html
=> INGEST-2133, Improve and document the release process

jack-core/src/com/rapleaf/jack/util/JackUtility.java, jack-test/test/java/com/rapleaf/jack/util/TestJackUtility.java
When building SQL statements for DATETIME and TIMESTAMP columns, include
milliseconds (fractional seconds precision of 3).
Jack represents DATETIME and TIMESTAMP types as ms held in longs, so it
is convenient to support the same level of precision when building SQL
statements.
It's been confirmed that althought MySQL 5.5 does not support storing
fractional seconds in time values, it can parse them; they'll be
truncated in the tables.
Jira: INGEST-2133
=> INGEST-2133, Support milliseconds

.gitignore, pom.xml
The `revision` property is used to consolidate the configuration of the
modules' versions.  Since we want to deploy these artifacts, that
property must be resolved in order for Maven to find the parents later.
See [Maven CI Friendly Versions][1]
[1]: https://maven.apache.org/maven-ci-friendly.html
=> Resolve revision property in POMs

Jenkinsfile, pom.xml
This more closely matches what we were building with in Travis CI: https://github.com/LiveRamp/jack/blob/a6a6561616db756aec7d2617862df20efc1d1a17/.travis.yml#L6 but uses a jdk that is available in our agents.
=> [OC-49258] build with java 11

jack-mysql/pom.xml, jack-test/pom.xml, pom.xml
Introduce a new SNAPSHOT that can use the newer mysql connector library.
=> [OC-49258] add mysql 8 connector on new snapshot
